
services:
  pg:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

  pgadmin:
    image: elestio/pgadmin
    restart: always
    environment:    
        - PGADMIN_DEFAULT_EMAIL=admin@localhost.com
        - PGADMIN_DEFAULT_PASSWORD=admin
        - PGADMIN_LISTEN_PORT=8080
    ports:
      - 8090:8080

  nginx:
    image: nginx
    environment:
      - SECRET_KEY=admin
    volumes:
      - ../backend/tmp:/usr/share/nginx/html
    ports:
      - "8080:80"

  labelstudio:
    image: heartexlabs/label-studio
    restart: always
    ports:
      - 8091:8080

  jupyter:
    build: jupyter
    environment:
      - SECRET_KEY=admin
    volumes:
      - ./notebooks:/notebooks
      - ./output:/app
    ports:
      - "8888:8888"
